name: "postman test action"
description: "Runs a Postman collection"
inputs:
  postman_api_key: # id of input
    description: "postman api key"
    required: true
    default: ""
  postman_api_url: # id of input
    description: "postman api url"
    required: true
    default: ""
  postman_collection_id: # id of input
    description: "postman collection id"
    required: true
    default: ""
  postman_env_id: # id of input
    description: "postman environment id"
    required: true
    default: ""
  slack_msg_webhook: # id of input
    description: "slack webhook url"
    required: true
    default: ""
  url_list_filename: # id of input
    description: "filename for the url json list"
    required: true
    default: ""
  host_url: # id of input
    description: "url to the host application server (replaces the host variable in postman)"
    required: true
    default: ""
  continue_if_fail: # id of input
    description: "throws an error if any tests fail"
    required: false
    default: ""
  continue_if_test_missing: # id of input
    description: "throws an error if any urls are not covered by tests"
    required: false
    default: ""
  request_timeout: # id of input
    description: "timeout amount for each request"
    required: false
    default: "29000"
outputs:
  output: # output will be available to future steps
    description: ""
runs:
  using: "node16"
  main: "dist/index.js"
